# Generated by Django 3.0.3 on 2020-02-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='No Title Set', max_length=200),
            preserve_default=False,
        ),
    ]
